// Code generated by protoc-gen-go. DO NOT EDIT.
// source: app.proto

/*
Package rpc is a generated protocol buffer package.

It is generated from these files:
	app.proto

It has these top-level messages:
	StoreReq
	StoreResp
	GetReq
	GetResp
	Account
	AuthenticateAccountResp
*/
package rpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StoreReq struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Val []byte `protobuf:"bytes,2,opt,name=val,proto3" json:"val,omitempty"`
}

func (m *StoreReq) Reset()                    { *m = StoreReq{} }
func (m *StoreReq) String() string            { return proto.CompactTextString(m) }
func (*StoreReq) ProtoMessage()               {}
func (*StoreReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *StoreReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *StoreReq) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type StoreResp struct {
}

func (m *StoreResp) Reset()                    { *m = StoreResp{} }
func (m *StoreResp) String() string            { return proto.CompactTextString(m) }
func (*StoreResp) ProtoMessage()               {}
func (*StoreResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type GetReq struct {
	Key string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
}

func (m *GetReq) Reset()                    { *m = GetReq{} }
func (m *GetReq) String() string            { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()               {}
func (*GetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetResp struct {
	Val []byte `protobuf:"bytes,1,opt,name=val,proto3" json:"val,omitempty"`
}

func (m *GetResp) Reset()                    { *m = GetResp{} }
func (m *GetResp) String() string            { return proto.CompactTextString(m) }
func (*GetResp) ProtoMessage()               {}
func (*GetResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetResp) GetVal() []byte {
	if m != nil {
		return m.Val
	}
	return nil
}

type Account struct {
	Username  string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	AccountID string `protobuf:"bytes,2,opt,name=accountID" json:"accountID,omitempty"`
	Password  string `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
}

func (m *Account) Reset()                    { *m = Account{} }
func (m *Account) String() string            { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()               {}
func (*Account) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Account) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *Account) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthenticateAccountResp struct {
	LoggedIn bool `protobuf:"varint,1,opt,name=loggedIn" json:"loggedIn,omitempty"`
}

func (m *AuthenticateAccountResp) Reset()                    { *m = AuthenticateAccountResp{} }
func (m *AuthenticateAccountResp) String() string            { return proto.CompactTextString(m) }
func (*AuthenticateAccountResp) ProtoMessage()               {}
func (*AuthenticateAccountResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *AuthenticateAccountResp) GetLoggedIn() bool {
	if m != nil {
		return m.LoggedIn
	}
	return false
}

func init() {
	proto.RegisterType((*StoreReq)(nil), "rpc.StoreReq")
	proto.RegisterType((*StoreResp)(nil), "rpc.StoreResp")
	proto.RegisterType((*GetReq)(nil), "rpc.GetReq")
	proto.RegisterType((*GetResp)(nil), "rpc.GetResp")
	proto.RegisterType((*Account)(nil), "rpc.Account")
	proto.RegisterType((*AuthenticateAccountResp)(nil), "rpc.AuthenticateAccountResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Cache service

type CacheClient interface {
	Store(ctx context.Context, in *StoreReq, opts ...grpc.CallOption) (*StoreResp, error)
	Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error)
}

type cacheClient struct {
	cc *grpc.ClientConn
}

func NewCacheClient(cc *grpc.ClientConn) CacheClient {
	return &cacheClient{cc}
}

func (c *cacheClient) Store(ctx context.Context, in *StoreReq, opts ...grpc.CallOption) (*StoreResp, error) {
	out := new(StoreResp)
	err := grpc.Invoke(ctx, "/rpc.Cache/Store", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cacheClient) Get(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error) {
	out := new(GetResp)
	err := grpc.Invoke(ctx, "/rpc.Cache/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Cache service

type CacheServer interface {
	Store(context.Context, *StoreReq) (*StoreResp, error)
	Get(context.Context, *GetReq) (*GetResp, error)
}

func RegisterCacheServer(s *grpc.Server, srv CacheServer) {
	s.RegisterService(&_Cache_serviceDesc, srv)
}

func _Cache_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StoreReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Cache/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Store(ctx, req.(*StoreReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Cache_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CacheServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Cache/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CacheServer).Get(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _Cache_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Cache",
	HandlerType: (*CacheServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _Cache_Store_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Cache_Get_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}

// Client API for AccountService service

type AccountServiceClient interface {
	Create(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error)
	Get(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error)
	Authenticate(ctx context.Context, in *Account, opts ...grpc.CallOption) (*AuthenticateAccountResp, error)
}

type accountServiceClient struct {
	cc *grpc.ClientConn
}

func NewAccountServiceClient(cc *grpc.ClientConn) AccountServiceClient {
	return &accountServiceClient{cc}
}

func (c *accountServiceClient) Create(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := grpc.Invoke(ctx, "/rpc.AccountService/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Get(ctx context.Context, in *Account, opts ...grpc.CallOption) (*Account, error) {
	out := new(Account)
	err := grpc.Invoke(ctx, "/rpc.AccountService/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accountServiceClient) Authenticate(ctx context.Context, in *Account, opts ...grpc.CallOption) (*AuthenticateAccountResp, error) {
	out := new(AuthenticateAccountResp)
	err := grpc.Invoke(ctx, "/rpc.AccountService/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AccountService service

type AccountServiceServer interface {
	Create(context.Context, *Account) (*Account, error)
	Get(context.Context, *Account) (*Account, error)
	Authenticate(context.Context, *Account) (*AuthenticateAccountResp, error)
}

func RegisterAccountServiceServer(s *grpc.Server, srv AccountServiceServer) {
	s.RegisterService(&_AccountService_serviceDesc, srv)
}

func _AccountService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AccountService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Create(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AccountService/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Get(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccountService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Account)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccountServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.AccountService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccountServiceServer).Authenticate(ctx, req.(*Account))
	}
	return interceptor(ctx, in, info, handler)
}

var _AccountService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.AccountService",
	HandlerType: (*AccountServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _AccountService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _AccountService_Get_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _AccountService_Authenticate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app.proto",
}

func init() { proto.RegisterFile("app.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0xcf, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0x99, 0x0b, 0xb0, 0x3d, 0x90, 0x98, 0x5e, 0x5c, 0x2a, 0x07, 0x52, 0x13, 0xb3, 0xd3,
	0x0e, 0x18, 0x6f, 0x5e, 0x08, 0x26, 0x84, 0xeb, 0x88, 0x67, 0x53, 0xcb, 0x0b, 0x10, 0x71, 0xad,
	0x6d, 0x87, 0xf1, 0x6f, 0xf1, 0x9f, 0x35, 0x6b, 0x37, 0x86, 0x86, 0x78, 0xeb, 0xe7, 0xbd, 0xef,
	0xf7, 0xfd, 0x4a, 0x21, 0xe6, 0x4a, 0x65, 0x4a, 0x4b, 0x2b, 0x49, 0xa8, 0x95, 0x60, 0x19, 0x44,
	0x2b, 0x2b, 0x35, 0xe6, 0xf8, 0x41, 0xae, 0x20, 0x7c, 0xc3, 0xaf, 0x24, 0x98, 0x04, 0x69, 0x9c,
	0x57, 0xcf, 0x2a, 0x72, 0xe0, 0xfb, 0xe4, 0x62, 0x12, 0xa4, 0xc3, 0xbc, 0x7a, 0xb2, 0x01, 0xc4,
	0xb5, 0xde, 0x28, 0x46, 0xa1, 0xb7, 0x40, 0x7b, 0xd6, 0xca, 0x6e, 0xa0, 0xef, 0x72, 0x46, 0x35,
	0x55, 0x82, 0xb6, 0xca, 0x0b, 0xf4, 0x67, 0x42, 0xc8, 0xb2, 0xb0, 0x84, 0x42, 0x54, 0x1a, 0xd4,
	0x05, 0x7f, 0xc7, 0xda, 0x7e, 0x64, 0x32, 0x86, 0x98, 0x7b, 0xd9, 0xf2, 0xc9, 0x0d, 0x11, 0xe7,
	0x6d, 0xa0, 0x72, 0x2a, 0x6e, 0xcc, 0xa7, 0xd4, 0xeb, 0x24, 0xf4, 0xce, 0x86, 0xd9, 0x03, 0x5c,
	0xcf, 0x4a, 0xbb, 0xc5, 0xc2, 0xee, 0x04, 0xb7, 0x58, 0x37, 0x73, 0xd3, 0x50, 0x88, 0xf6, 0x72,
	0xb3, 0xc1, 0xf5, 0xb2, 0x70, 0x0d, 0xa3, 0xfc, 0xc8, 0xd3, 0x67, 0xe8, 0xce, 0xb9, 0xd8, 0x22,
	0x49, 0xa1, 0xeb, 0xd6, 0x24, 0x97, 0x99, 0x56, 0x22, 0x6b, 0x4e, 0x44, 0x47, 0xa7, 0x68, 0x14,
	0xeb, 0x10, 0x06, 0xe1, 0x02, 0x2d, 0x19, 0xb8, 0x84, 0xbf, 0x06, 0x1d, 0xb6, 0x50, 0x69, 0xa6,
	0xdf, 0x01, 0x8c, 0xea, 0x11, 0x56, 0xa8, 0x0f, 0x3b, 0x81, 0xe4, 0x0e, 0x7a, 0x73, 0x8d, 0xdc,
	0x22, 0xf1, 0xe2, 0x3a, 0x4d, 0x7f, 0x11, 0xeb, 0x90, 0x5b, 0x5f, 0xfe, 0x7f, 0xd1, 0x23, 0x0c,
	0x4f, 0xb7, 0xfd, 0xa3, 0x1e, 0x7b, 0x3a, 0x7f, 0x0e, 0xd6, 0x79, 0xed, 0xb9, 0xef, 0x70, 0xff,
	0x13, 0x00, 0x00, 0xff, 0xff, 0x51, 0x27, 0x8b, 0xc4, 0x1b, 0x02, 0x00, 0x00,
}
